# Generated by Django 4.2 on 2023-04-07 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0002_resource_seasonlocation_suggestion_produce_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='produce',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='seasonpal.produce'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to=settings.AUTH_USER_MODEL),
        ),
    ]
