# Generated by Django 4.2 on 2023-04-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0003_alter_note_produce_alter_note_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonlocation',
            name='combo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
