# Generated by Django 4.2 on 2023-04-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0004_seasonlocation_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonlocation',
            name='combo',
            field=models.CharField(max_length=100),
        ),
    ]
