# Generated by Django 4.2 on 2023-04-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0006_alter_seasonlocation_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='seasonlocations',
        ),
        migrations.AddField(
            model_name='seasonlocation',
            name='produce',
            field=models.ManyToManyField(to='seasonpal.produce'),
        ),
    ]
