# Generated by Django 4.2 on 2023-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0007_remove_produce_seasonlocations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='more_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
