# Generated by Django 4.2 on 2023-04-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0008_produce_more_info_alter_produce_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='more_info',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='produce',
            name='link2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='link3',
            field=models.TextField(blank=True),
        ),
    ]
