# Generated by Django 4.2 on 2023-04-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0009_rename_more_info_produce_link1_produce_link2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='produce',
            new_name='produce_id',
        ),
    ]
