# Generated by Django 4.2 on 2023-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0014_alter_note_produce_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='produce',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
