# Generated by Django 4.2 on 2023-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0019_alter_note_produce_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='produce',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.IntegerField(),
        ),
    ]
