# Generated by Django 4.2 on 2023-04-15 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0036_remove_note_produce_remove_note_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='produce',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
