# Generated by Django 4.2 on 2023-04-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0039_remove_suggestion_user_suggestion_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='author',
            new_name='user',
        ),
    ]
