# Generated by Django 4.2 on 2023-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonpal', '0040_rename_author_suggestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
